# Generated by Django 5.0.7

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reference", models.CharField(max_length=24, unique=True)),
                ("customer_key", models.CharField(db_index=True, max_length=64)),
                ("customer_name", models.CharField(max_length=120)),
                ("delivery_address", models.CharField(max_length=240)),
                ("robot_unit", models.CharField(max_length=32)),
                ("subject", models.CharField(max_length=180)),
                ("description", models.TextField()),
                ("status", models.CharField(choices=[("open", "Open"), ("waiting", "Waiting"), ("resolved", "Resolved")], default="open", max_length=16)),
                ("priority", models.CharField(choices=[("low", "Low"), ("normal", "Normal"), ("high", "High"), ("urgent", "Urgent")], default="normal", max_length=16)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("original_name", models.CharField(max_length=180)),
                ("stored_name", models.CharField(max_length=240)),
                ("uploaded_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ticket", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="portal.ticket")),
            ],
        ),
        migrations.CreateModel(
            name="TicketNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("author", models.CharField(max_length=80)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ticket", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notes", to="portal.ticket")),
            ],
            options={"ordering": ["created_at"]},
        ),
    ]
